name: backend
description: "Klooigeld"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/rewards/
    - assets/json/
    - assets/fonts/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    #LOGO FONT 1
    - family: PurpleMagic
      fonts:
        - asset: assets/fonts/Purple_Magic.ttf

    #LOGO FONT 2
    - family: PurpleMagicSVG
      fonts:
        - asset: assets/fonts/Purple-Magic-SVG.otf

    # TITLE FONT
    - family: NeighborBlack
      fonts:
        - asset: assets/fonts/Neighbor_Black.otf

    # NORMAL TEXT FONT
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic

